#!/bin/sh

# Генерация Swagger, если изменён handler.go в любой подпапке internal/handler/
if git diff --cached --name-only | grep -E "internal/handler/[^/]+/handler\.go$" | grep -q .; then
    echo "Regenerating Swagger docs..."
    go generate ./...
    git add docs/
fi

if git diff --cached --name-only | grep -E "docs/[^/]+$" | grep -q .; then
    echo "Docs can not be modified directly"
    exit 1
fi

# Выход с кодом 0, если всё хорошо, с кодом 1 — чтобы прервать коммит
exit 0
