// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/creds/login": {
            "post": {
                "description": "Returns access token in body and sets refresh token to cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "CredentialsLogin into by email and password",
                "parameters": [
                    {
                        "description": "CredentialsLogin request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CredentialsLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponce"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    }
                }
            }
        },
        "/auth/creds/reg/link/confirm": {
            "post": {
                "description": "Verifies token from link and register user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email and register user",
                "parameters": [
                    {
                        "description": "CredentialsRegisterLinkConfirm request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CredentialsRegisterLinkConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.emptyResponce"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    }
                }
            }
        },
        "/auth/creds/reg/link/send": {
            "post": {
                "description": "Sends registration link with token in query to provided email address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sends registration link to email",
                "parameters": [
                    {
                        "description": "Send link request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CredentialsRegisterLinkSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.emptyResponce"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "description": "Clears refresh token from cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout from account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.emptyResponce"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    }
                }
            }
        },
        "/auth/token/refresh": {
            "get": {
                "description": "Refreshs access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "TokenRefresh access token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.TokenRefreshResponce"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.errorResponce"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.CredentialsLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "Test_1234"
                },
                "username": {
                    "type": "string",
                    "example": "test@mail.ru / test"
                }
            }
        },
        "auth.CredentialsRegisterLinkConfirmRequest": {
            "type": "object",
            "required": [
                "password",
                "passwordRepeat",
                "token",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "Test_1234"
                },
                "passwordRepeat": {
                    "type": "string",
                    "example": "Test_1234"
                },
                "token": {
                    "type": "string",
                    "example": "a17a89b6-eff8-4b05-9be7-407d62b46c4a"
                },
                "username": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "auth.CredentialsRegisterLinkSendRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@mail.ru"
                }
            }
        },
        "auth.LoginResponce": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "gG3d83bJk5jawy31...WE4u"
                }
            }
        },
        "auth.TokenRefreshResponce": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "gG3d83bJk5jawy31...WE4u"
                }
            }
        },
        "httputil.emptyResponce": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "httputil.errorResponce": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string",
                    "example": "error description"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Role-Play-Dev Gateway service API documentation",
	Description:      "Backend Gateway service API of a tabletop RPG helper",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
