basePath: /api/v1
definitions:
  auth.CredentialsLoginRequest:
    properties:
      password:
        example: Test_1234
        type: string
      username:
        example: test@mail.ru / test
        type: string
    required:
    - password
    - username
    type: object
  auth.CredentialsRegisterLinkConfirmRequest:
    properties:
      password:
        example: Test_1234
        type: string
      passwordRepeat:
        example: Test_1234
        type: string
      token:
        example: a17a89b6-eff8-4b05-9be7-407d62b46c4a
        type: string
      username:
        example: test
        type: string
    required:
    - password
    - passwordRepeat
    - token
    - username
    type: object
  auth.CredentialsRegisterLinkSendRequest:
    properties:
      email:
        example: test@mail.ru
        type: string
    required:
    - email
    type: object
  auth.LoginResponce:
    properties:
      accessToken:
        example: gG3d83bJk5jawy31...WE4u
        type: string
    type: object
  auth.TokenRefreshResponce:
    properties:
      accessToken:
        example: gG3d83bJk5jawy31...WE4u
        type: string
    type: object
  httputil.emptyResponce:
    properties:
      code:
        type: integer
    type: object
  httputil.errorResponce:
    properties:
      code:
        type: integer
      message:
        example: error description
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Backend Gateway service API of a tabletop RPG helper
  termsOfService: http://swagger.io/terms/
  title: Role-Play-Dev Gateway service API documentation
  version: "1.0"
paths:
  /auth/creds/login:
    post:
      consumes:
      - application/json
      description: Returns access token in body and sets refresh token to cookie
      parameters:
      - description: CredentialsLogin request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.CredentialsLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.errorResponce'
      summary: CredentialsLogin into by email and password
      tags:
      - auth
  /auth/creds/reg/link/confirm:
    post:
      consumes:
      - application/json
      description: Verifies token from link and register user
      parameters:
      - description: CredentialsRegisterLinkConfirm request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.CredentialsRegisterLinkConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.emptyResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.errorResponce'
      summary: Verify email and register user
      tags:
      - auth
  /auth/creds/reg/link/send:
    post:
      consumes:
      - application/json
      description: Sends registration link with token in query to provided email address
      parameters:
      - description: Send link request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.CredentialsRegisterLinkSendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.emptyResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.errorResponce'
      summary: Sends registration link to email
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: Clears refresh token from cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputil.emptyResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.errorResponce'
      summary: Logout from account
      tags:
      - auth
  /auth/token/refresh:
    get:
      consumes:
      - application/json
      description: Refreshs access token using refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenRefreshResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.errorResponce'
      summary: TokenRefresh access token
      tags:
      - auth
swagger: "2.0"
