# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go: generate & build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.5'

    - name: Generate
      run: | 
        if git diff --cached --name-only | grep -E "internal/handler/[^/]+/handler\.go$" | grep -q .; then
            go generate ./...
        fi

    - name: Check for changes
      id: git-check
      run: |
        git status --porcelain
        if [[ -z $(git status --porcelain) ]]; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated code generation [skip ci]"
        git push
